import Head from "next/head";
import Image from "next/image";
import Header from "../components/header";
import logo from "../images/trady_logo.svg";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header
        logo={logo}
        alt="trady"
        text="Point your domain at "
        url="https://trady.com/"
      />
    </>
  );
}
